branches:
  only:
    - master

environment:
  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "32"

# Disabled as unnecessary
#    - PYTHON: "C:\\Python27-x64"
#      PYTHON_VERSION: "2.7.x" # currently 2.7.9
#      PYTHON_ARCH: "64"
#
#    - PYTHON: "C:\\Python33"
#      PYTHON_VERSION: "3.3.x" # currently 3.3.5
#      PYTHON_ARCH: "32"
#
#    - PYTHON: "C:\\Python33-x64"
#      PYTHON_VERSION: "3.3.x" # currently 3.3.5
#      PYTHON_ARCH: "64"
#
#    - PYTHON: "C:\\Python34"
#      PYTHON_VERSION: "3.4.x" # currently 3.4.3
#      PYTHON_ARCH: "32"
#
#    - PYTHON: "C:\\Python34-x64"
#      PYTHON_VERSION: "3.4.x" # currently 3.4.3
#      PYTHON_ARCH: "64"

install:
  - pip install -r requirements.txt
  - python setup.py install

build: false

before_test:
  - pip install -r test-requirements.txt

test_script:
  - nosetests --cover-inclusive --cover-erase --cover-package=dvc --with-coverage

after_test:
  - if "%APPVEYOR_REPO_TAG%"=="true" .\scripts\build_windows.cmd

artifacts:
  - path: dvc*.exe
    name: DVC Installer

deploy:
  provider: GitHub
  auth_token:
    secure: 25c1pNoXWbtTwUkKLcThwcl2A2xG8oXHsPuD73HVbQ7SRy9X6HzkCc2sXzhpfRtF
  on:
    appveyor_repo_tag: true
