branches:
  only:
    - master

platform: x86

environment:
  aws_access_key_id:
    secure: veTfhOrd4wUpG7NlRsvS3tufuaFfST8i7SZa2HVH6Vc=
  aws_secret_access_key:
    secure: nCQcN/Mzce0erwcNOU3yAuWgF6ZuTvPBEqTF3XFp1poGcDbSIg+s67eVxsxWCXQj
  GOOGLE_APPLICATION_CREDENTIALS: c:/gcp_creds.json
  GCP_CREDS:
    secure: DcnD7MD4IYiiHtJQZF9G7+wzF934sUm5S3ZL/WDDW43eVY+Zz7d4ScjxUFP9R4/7Qw9ejsHq7IboDbG6/BDYbR/CYSdVoGDhE2pfe499P3t3mJ/WSsILzmUbCnqOJw/YfkZkzf2yhg9cLfibvFSxkoh6b+I4cdfLxq79TDppH7/wBOOd/lQvQD1KClRyE1wSe9N0cVqWgr6/fxPixcRNtGzKd/OymlpznmfCVD9waIqON4PfQ5Kdwhmetik7Sg+nxFKyT0RmwBBgxM606rp0qWmMps7PJH6TmiLuhgHjsNTCmupsnHuBKn+o2/zt/cOG9J6zGDc+32cqre8iDLJteITt/An3bY4nk4aTq0b/J3KMT4M0nwDlnQ+RTSDYzTqqR/fwkhvNqjUvP5yCzb+FzzzvJQ6teUJPIc3yi/qhAlEZroxEm0dELODR+61+rQXE9ihdTv3hSpzRKz1rhMbDVU5VRlgW6SaUyNE5szsxbvOVl6O5FB6FkMIUSuX3fA91U2H2g3eBTJlsKQZPOUrxEQJCh9z8ITJXDKRNksj5Hexcx2AGpQrvNk9uAoyh59pjeuP6rU9RVH1mRZ0fKypDEwNF+F8eMSPW2jfEZp5zCXkImEPL8M3TMhMhsOgQbnokOPIlCiNBwRirg5vUDpjtwwU+jOM5dzYg9UNcnRZAX9w49cw8CiIWQeItI7vHHH7oE10R5/+DtRiB+OxjA2XgWnSMsS1zas175NqoEEbv8AzLm9+E2074s03GCPnmhtZYp1ofdrQskUGn4p1CLtDWCaop2+B/FINZIHM8Xvn6TX7aPxRI7ZHMpJjNJSj8nOH4J4mtTpwcCRUTWT3i3a3jksmW3pSFf6rt01GnVbT+W4rSygn2+BR+qMMba93uhSYTCC4jHtNchT3liY8kQiQWHDbY3dR0+7rWwg0z4nEZ7/6dvgQ2Ogf+mvrNlGXHEjO1dVMCEeNMnyOO1CDKBqRmumZFaX78bbpBrjK7uYEDaeLSFCvdZLI3/Qv9yZNKz41SNHD0jqNeKIJX1QQ7BzeGuhGyluu7NqCVgb+oj7sO2k0pztVofwUJ8QGe85vslw8CJQMx6WFpgR1vl2/InBifbaewqzy3XRDJdBSUxTSMmpwnxdE2Ivbq1vmYrGiuDWeRH7+w2BPBtaMu6LL91n1A3jWCVvk7l1whazumd4f4xMmb9U8nz7sfoKGcbxko2l9YJILa6CK9E+/o2/pcLl4FQxe0z4Ux1LX0VS6UAy6frlbuZuQ8BU7cxxFSIz1sZD3+cgXAf8kmEBhKYinbefushdrpuQAZrhoiEJnjuSNTdsEQC1w5To0A+VyPGSF62/im3p+BFW0MF4K7nDQ+3ixl6UIM7IIRiR75EFo3Kq+HWEtmql4fep0FiLjX4jyJ/fhXBRV6WKjAdN7XHkRDtYLIryrULJqH3SdaKP2ZKvnIFohU3JV9edvYBQVFW0gfi4yN0dS9jfneQ3eLnF8foHFiJmM8c/3Mdr3KKKZgcSW03hDn5IluIfGksce0vtneGj7FFD4em27dT3mQsHks9qk2DQfqIW6DcNBNzXq7FSW1CVo5edcBdi42ntbKs5rz0wNWAoZXcFdQww5xLcWO5oJulBr89HMJfaob+mXrFFlWbHgQWaSlRHvfR8/8MOkJn0lK604mIS4CUCCThYyWY2X/nwAbpD6O+c1p+xbNBECNLZUMddFxYMwNlCLm4js1jaiZ0f79sjCvc2lktOBGXrNtXfZPtYcO1txgSZtLrCahvPWKycoPsgYO27HKxZmQN0p46IVAoQtu0CdaA3KJjXYmqpp+1FVXyXLuq7nJb4hrZLixiwCwTGDzJoSP9Bjq4ZdKhgnRWmjMxxEAoZ62Y9RQYOc01ipJWy0d9gq72b8p6xRcE64amdUUg0Ym+WmbB+kE6qeuNpp6uiAB0GbDuoRtApDzXxRs+WEN0+ZP7slqaC/IHde7O4C1avIzvbXn8p9bJLIdPgGkrBtHo2WkRR+5yJUGwHPkxQh8uU8pmLlU36d8CNZrmtg7Isjf+T9KrvpziqffUwoFqOEUHJlS9J9+O1UB6bN+E4WyYaxnZ/PWVpOw9XEYglpfPOnBFby/qVNoZAMPnci9NT5tR9uPxKOHgiNrsTqjN+RLiybyutEqHbRsnKoB74+Wc4DtireOdaGEF0TF0JDXuU1T15PhqzyrhAwExgj4Vl0cEMFkwQ1tFbUl2IarvgUQpXW0STo+1GiNPoZbSXqXRRCwj+s2miQP9FNg6eGu5xTBJRPpVLm4qS/0RXOjugXOGmzUqdkbVnjGqPCcKif/wZR+VwtOtPqy45lcptaUo9YfARky4s+pzeUOk5X5FcnEZPYWRUsX1e24v4wXRXEsXr5mESgDEOJeXklHwtlE3D0NS2TWabvLk0LLeCSavTwAyD5JRbWWB4Pu280pDECmjfOSdpzqj744GQxHOEvR5o4knvIn3tNbCexM9XKwJOgMJAzebTrfmUfICXXG++neScANFNWv6exFYx7AzKq1ivgyMduNAljKeTEQqUOFgqammXqaKLVGKpoWfQSYNJCNt057mmxw39rpanEp1F/aPwBa5yU3Z3VFX+EpH+8QaqFondxCNCgFE7huDaWRg4WMS5BXhmZ49hkVPFvHlO+BVkunFgcasSBxQ07tEOskcSK79/VmlQFWREDOI8UAjSfVlYbSac44FWS5k539rIG9BCYegUDEN9v5pAKuuiSA01Tjum4x4u9HosRaZODphcHoSyObs/+fGOLvpi4jeZ0i6cH+bzTdBuv3/EKIKAzTWqu2Tf2q43dxGxC9H2DoxBOLgslcKOMq0Ns9I5JHH+0jBQ/S1HCgdvIKwu3VwxkSCnmnARcMgtmzCOXszCZYgMb7F/AFqQTDUaZ3tjjv4e7LQxyEerhw251CW1lNRWPOqhiKJ1CJ7qUaX4CFfJWythXU8IaI5h3ArXrnmloruEu3ImaIGQQfhNt0iBt+aLBvoHkvRxD8JPtoQOVnsX/wbBWqBvWWkiLbM3FtbiRKTbc3UMoD8VzpMGsX5FLiMpLpmb3sF4JPZYUiAEPyC/XRMJExoBECzHYm7Ovh/w==

  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "32"

# Disabled as unnecessary
#    - PYTHON: "C:\\Python27-x64"
#      PYTHON_VERSION: "2.7.x" # currently 2.7.9
#      PYTHON_ARCH: "64"
#
#    - PYTHON: "C:\\Python33"
#      PYTHON_VERSION: "3.3.x" # currently 3.3.5
#      PYTHON_ARCH: "32"
#
#    - PYTHON: "C:\\Python33-x64"
#      PYTHON_VERSION: "3.3.x" # currently 3.3.5
#      PYTHON_ARCH: "64"
#
#    - PYTHON: "C:\\Python34"
#      PYTHON_VERSION: "3.4.x" # currently 3.4.3
#      PYTHON_ARCH: "32"
#
#    - PYTHON: "C:\\Python34-x64"
#      PYTHON_VERSION: "3.4.x" # currently 3.4.3
#      PYTHON_ARCH: "64"

install:
  - cinst graphviz
  - cinst wget
  - cinst awscli
  - cinst gsutil
  - wget --no-check-certificate https://github.com/dpinney/omf/raw/master/omf/static/pygraphviz-1.3.1-cp27-none-win32.whl
  - pip install pygraphviz-1.3.1-cp27-none-win32.whl
  - pip install -r requirements.txt
  - python setup.py install

build: false

before_test:
  - aws configure set aws_access_key_id "%aws_access_key_id%"
  - aws configure set aws_secret_access_key "%aws_secret_access_key%"
  - python .\scripts\ci\gcp_setup.py
  - pip install -r test-requirements.txt

test_script:
  - nosetests --cover-inclusive --cover-erase --cover-package=dvc --with-coverage

after_test:
  - if "%APPVEYOR_REPO_TAG%"=="true" .\scripts\build_windows.cmd

artifacts:
  - path: dvc*.exe
    name: DVC Installer

deploy:
  provider: GitHub
  auth_token:
    secure: 25c1pNoXWbtTwUkKLcThwcl2A2xG8oXHsPuD73HVbQ7SRy9X6HzkCc2sXzhpfRtF
  on:
    appveyor_repo_tag: true
