branches:
  only:
    - master
    - devel

platform: x86

environment:
  aws_access_key_id:
    secure: veTfhOrd4wUpG7NlRsvS3tufuaFfST8i7SZa2HVH6Vc=
  aws_secret_access_key:
    secure: nCQcN/Mzce0erwcNOU3yAuWgF6ZuTvPBEqTF3XFp1poGcDbSIg+s67eVxsxWCXQj
  GCP_CREDS:
    secure: 96fJ3r2i2GohbXHwnSs5N4EplQ7q8YmLpPWM0AC+f4s=
  CODECOV_TOKEN:
    secure: XN4jRtmGE5Bqg8pPZkwNs7kn3UEI73Rkldqc0MGsQISZBm5TNJZOPofDMc1QnUsf
  AZURE_STORAGE_CONTAINER_NAME: appveyor-tests
  AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;

  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "32"

# Disabled as unnecessary
#    - PYTHON: "C:\\Python27-x64"
#      PYTHON_VERSION: "2.7.x" # currently 2.7.9
#      PYTHON_ARCH: "64"
#
#    - PYTHON: "C:\\Python33"
#      PYTHON_VERSION: "3.3.x" # currently 3.3.5
#      PYTHON_ARCH: "32"
#
#    - PYTHON: "C:\\Python33-x64"
#      PYTHON_VERSION: "3.3.x" # currently 3.3.5
#      PYTHON_ARCH: "64"
#
#    - PYTHON: "C:\\Python34"
#      PYTHON_VERSION: "3.4.x" # currently 3.4.3
#      PYTHON_ARCH: "32"
#
#    - PYTHON: "C:\\Python34-x64"
#      PYTHON_VERSION: "3.4.x" # currently 3.4.3
#      PYTHON_ARCH: "64"

install:
  - ps: Install-Product node
  - npm install -g azurite
  - ps: $AzuriteProcess = Start-Process azurite-blob -PassThru
  - cinst wget
  - cinst awscli
  - cinst gcloudsdk
  - refreshenv
  - cinst gsutil
  - cinst openssl.light --version 1.1.1
  - python -m pip install -U pip setuptools wheel
  - pip install -r requirements.txt
  - python setup.py install

build: false

before_test:
  - aws configure set aws_access_key_id "%aws_access_key_id%"
  - aws configure set aws_secret_access_key "%aws_secret_access_key%"
  - aws configure set region us-east-2
  - openssl enc -d -aes-256-cbc -md md5 -k "%GCP_CREDS%" -in scripts\ci\gcp-creds.json.enc -out scripts\ci\gcp-creds.json & exit 0
  - pip install -r test-requirements.txt

test_script:
  - python -mtests

after_test:
  - if "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" codecov
  - if "%APPVEYOR_REPO_TAG%"=="true" python -m dvc pull
  - if "%APPVEYOR_REPO_TAG%"=="true" .\scripts\build_windows.cmd

on_finish:
  - ps: Stop-Process $AzuriteProcess

artifacts:
  - path: dvc*.exe
    name: DVC Installer

deploy:
  provider: GitHub
  auth_token:
    secure: 25c1pNoXWbtTwUkKLcThwcl2A2xG8oXHsPuD73HVbQ7SRy9X6HzkCc2sXzhpfRtF
  on:
    appveyor_repo_tag: true
