version: "2"
checks:
    argument-count:
        config:
            threshold: 8
    complex-logic:
        config:
            threshold: 6
    file-lines:
        config:
            threshold: 350
    method-complexity:
        config:
            threshold: 15
    method-count:
        config:
            threshold: 30
exclude_patterns:
    - tests
