repos:
- hooks:
  - id: black
    language_version: python3
  repo: https://github.com/ambv/black
  rev: 19.10b0
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
    -   id: seed-isort-config
- hooks:
  - id: isort
    language_version: python3
  repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
- hooks:
  - id: flake8
    language_version: python3
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
- hooks:
  - args:
    - -i
    - '2'
    id: beautysh
    language_version: python3
  repo: https://github.com/lovesegfault/beautysh
  rev: master
- hooks:
  - id: dvc-pre-commit
    language_version: python3
    stages:
    - commit
  - id: dvc-pre-push
    language_version: python3
    stages:
    - push
  - always_run: true
    id: dvc-post-checkout
    language_version: python3
    stages:
    - post-checkout
  repo: https://github.com/iterative/dvc
  rev: master
