repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    - id: flake8
      language_version: python3
-   repo: https://github.com/casperdcl/sh
    rev: master
    hooks:
    - id: shfmt
      language: golang
      args:
      - -l  # list files whose formatting differs from shfmt's
      - -d  # error with a diff when the formatting differs
      - -i  # indentation
      - '2' # 2 spaces
      - -ci  # switch cases will be indented
