---
restylers:
  - name: black
    image: restyled/restyler-black:v19.10b0
    command:
    - black
    arguments: []
    include:
    - "**/*.py"
    interpreters:
    - python
  - name: isort
    image: restyled/restyler-isort:v5.4.2
    command:
    - isort
    arguments: []
    include:
    - "**/*.py"
    interpreters:
    - python
