---
restylers:
  - name: black
    image: restyled/restyler-black:v19.3b0
    command:
    - black
    arguments: []
    include:
    - "**/*.py"
    interpreters:
    - python
  - name: reorder-python-imports
    image: restyled/restyler-reorder-python-imports:v1.6.0
    command:
    - reorder-python-imports
    - "--exit-zero-even-if-changed"
    arguments: []
    include:
    - "**/*.py"
    interpreters:
    - python
