language: python
sudo: required
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5"
#  - "3.6" Not supported by pyinstaller yet
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - git config --global user.email "dvctester@example.com"
  - git config --global user.name "DVC Tester"
  - mkdir -p ~/.aws && printf "[default]\naws_access_key_id = ABCDEFG\naws_secret_access_key = 123456789" > ~/.aws/credentials
script:
  - ./unittests.sh
  - ./build_linux.sh
  - ./build_package.sh
after_sucess:
  - CODECLIMATE_REPO_TOKEN=7350efa14a67c3911af96dadaabe811b43eead7b466309b47687499bf5d72287 codeclimate-test-reporter
deploy:
  provider: releases
  api_key:
    secure: sqVsxsM8meieL/1NwvUzZsdTg2nvklzJfGsxhjv6bjSEenih4RmWGMTSLA6+Fxryu/WF87b/gYi7zgIxGh08dutvV1M/La46Dn6ix6rc/Z68aHGiLyjQy2mTUYGCv/mJfXq9fohZUc/0e+X5WeZsr4TT7k9HTAJl0/MpdjFy18lAZwYnYHATnus3ZKV73Q/vZK/4tX9of8XUNM8T+yZZ0EP/29/K38Q89wuFmqe19YC4kkoiEG5PCYwm/dMFVoGHDoSix4zfwim5erBcN94b2d9whD5TM5+Xrm8YpH/eWRvMeBC/kEIWBh7KnTyR9nSEtpbwkkCVgC5r+YfubaQScnQsVvwj93hPKvCFLwrOVXeo9nnXiGEYB6JnmGievB0dpUxh9+jxJxICAsNp6efrc1kfY6MJ1J1JvREt8ISuJk/9bwmmQF1TA1agzM6tgb421WgS2pyjWcA25gjkrkhFeXcyAuun17hgEkEwIIuI0eBogsjgDPU6i3GEIoAS58MGi/Tl+drvjhsAsLM1nWLg3uHFfsM85k0142s9KzxsSgae/Qn+WXiDWMGCppAIsm6j2DnNpQajKVOxMfkQtVkDaOFHOy4zC40sATDu89TQnK5lojk2x68nsAJ6uocSqz9QLAXa9BVZW1M5xIzkI/X5b9T1tapXFdoVhMM7BMuBIzY=
  file_glob: true
  file:
    - dvc*.rpm
    - dvc*.deb
  skip_cleanup: true
  on:
    tags: true
    repo: dataversioncontrol/dvc
