language: python
cache:
  - pip
  - directories:
    - /opt/python
    - $HOME/.pyenv
sudo: true
dist: xenial
python: "3.7"
env:
  global:
    - PYENV_ROOT="$HOME/.pyenv"
    - PATH="$PYENV_ROOT/bin:$PATH"
# Travis doesn't support testing python on Mac yet, so we need
# to workaround it by installing it directly with brew.
#
# Note that we specify language as ruby-2.4.0 to help us satisfy
# fpm dependencies, as travis runs el capitan with an old ruby
# version, that causes fpm to crash.
matrix:
  include:
  - name: "2.7"
    env:
    - PYTHON_VER=2.7.13
  - name: "3.5"
    env:
    - PYTHON_VER=3.5.3
  - name: "3.6"
    env:
    - PYTHON_VER=3.6.2
  - name: "3.7"
    env:
    # NOTE: using default python
    - PYTHON_VER=
  - if: type = cron OR tag is present
    os: osx
    osx_image: xcode7.3
    language: ruby
    rvm: 2.4.0
    env:
    - PYTHON_VER=2.7.10
    - CPPFLAGS="-I/usr/local/opt/openssl/include $CPPFLAGS"
    - LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"
    - PYTHON_CONFIGURE_OPTS="--enable-framework"
  - if: type = cron OR tag is present
    os: osx
    osx_image: xcode7.3
    language: ruby
    rvm: 2.4.0
    env:
    - PYTHON_VER=3.6.2
    - PYTHON_CONFIGURE_OPTS="--enable-framework"
  - if: type = cron OR tag is present
    os: osx
    osx_image: xcode7.3
    language: ruby
    rvm: 2.4.0
    env:
    - PYTHON_VER=3.5.0
    - PYTHON_CONFIGURE_OPTS="--enable-framework"
  - if: type = cron OR tag is present
    os: osx
    osx_image: xcode10.1
    language: ruby
    rvm: 2.4.0
    env:
    - PYTHON_VER=2.7.10
    - CPPFLAGS="-I/usr/local/opt/openssl/include $CPPFLAGS"
    - LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"
    - PYTHON_CONFIGURE_OPTS="--enable-framework"
  - if: type = cron OR tag is present
    os: osx
    osx_image: xcode10.1
    language: ruby
    rvm: 2.4.0
    env:
    - PYTHON_VER=3.5.0
    - PYTHON_CONFIGURE_OPTS="--enable-framework"
before_install:
  - bash ./scripts/ci/before_install.sh
  - source env.sh
  - python --version
install:
  - bash ./scripts/ci/install.sh
script:
  - bash ./scripts/ci/script.sh
deploy:
  condition: "[[ $(./scripts/ci/deploy_condition.sh) == 'true' ]]"
  provider: releases
  api_key:
    secure: nyo17gF4Xl6DFL/KVkMewC805Cv+eK99L7SiYCU+WUAYDIzzFL3YJm7fm8bznPeor7DmpO7uSLSveMnJETBtdurW6JWhCTUss4yD66yFzpk6Z5cvHf/1UA5pdMHkkMM54fRaTRt6L2Yal7RPwGEQTBECLXW1Xmf78Y6+0l8lTvXQ9jXOQSRO/63VDKI5Zww2+XytVicUFlr0hLMGKUuaCjjXcQlAPzBgQz3/5Iz6EtzeTf2o+gTPjocbRbSFPikfiBXUn8XlJ8jBj7i114XJRJffw59KxYGDzxp+enfLBULGNoW0Np2hZqkKkPUIdB08C8XVbRXlFYX8cEYBczjqhv8A05p5F5CnltnqQ0KazcoUP2awPVqn68dWNRF+kqrnMBus8euYKIZ4dy/6bVEKJRa84ESJXZVDcwXTAXRqyovSxOlXqg9ZgAImMKBfKn/fpDX2xIvQPaXcnJxKbmcePfdbC1d0HYJ5jkbNaxKE/T15VvhzIho7mJ2WAv1r8QouQUuzqtpzIGbRn/KXHRUzCtyP0k4+eMKMLFOPzg848WsDarP3v8VYiSy4nFY7ZP7DRd3KttvW5bgVbSeO4jPmTgS6TnnpRwual9BJXSG7bjbfpIMii3bNZ7jWL4zpKT9Jfm8w9RGKLcX9HqkZ3+y60+LtYdhEfBvqsIlWQoIJBXg=
  file_glob: true
  file:
    - dvc*.rpm
    - dvc*.deb
    - dvc*.pkg
  skip_cleanup: true
  on:
    tags: true
    repo: iterative/dvc
