language: python
sudo: required
dist: trusty
group: deprecated-2017Q4
python:
  - "2.7"
  - "3.4"
  - "3.5"
#  - "3.6" Not supported by pyinstaller yet
cache: pip
# Travis doesn't support testing python on Mac yet, so we need
# to workaround it by installing it directly with brew.
#
# Note that we specify language as ruby-2.4.0 to help us satisfy
# fpm dependencies, as travis runs el capitan with an old ruby
# version, that causes fpm to crash.
matrix:
  include:
  - os: osx
    osx_image: xcode7.3
    language: ruby
    rvm: 2.4.0
    env: PYTHON_VER=2.7.10
  - os: osx
    osx_image: xcode7.3
    language: ruby
    rvm: 2.4.0
    env: PYTHON_VER=3.4.3
  - os: osx
    osx_image: xcode7.3
    language: ruby
    rvm: 2.4.0
    env: PYTHON_VER=3.5.0
before_install:
  - bash ./scripts/ci/before_install.sh
install:
  - bash ./scripts/ci/install.sh
before_script:
  - bash ./scripts/ci/before_script.sh
script:
  - bash ./scripts/ci/script.sh
after_script:
  - bash ./scripts/ci/after_script.sh
deploy:
  condition: "[[ $(python -c 'import sys; print(sys.version_info[0])') == '2' ]]"
  provider: releases
  api_key:
    secure: nyo17gF4Xl6DFL/KVkMewC805Cv+eK99L7SiYCU+WUAYDIzzFL3YJm7fm8bznPeor7DmpO7uSLSveMnJETBtdurW6JWhCTUss4yD66yFzpk6Z5cvHf/1UA5pdMHkkMM54fRaTRt6L2Yal7RPwGEQTBECLXW1Xmf78Y6+0l8lTvXQ9jXOQSRO/63VDKI5Zww2+XytVicUFlr0hLMGKUuaCjjXcQlAPzBgQz3/5Iz6EtzeTf2o+gTPjocbRbSFPikfiBXUn8XlJ8jBj7i114XJRJffw59KxYGDzxp+enfLBULGNoW0Np2hZqkKkPUIdB08C8XVbRXlFYX8cEYBczjqhv8A05p5F5CnltnqQ0KazcoUP2awPVqn68dWNRF+kqrnMBus8euYKIZ4dy/6bVEKJRa84ESJXZVDcwXTAXRqyovSxOlXqg9ZgAImMKBfKn/fpDX2xIvQPaXcnJxKbmcePfdbC1d0HYJ5jkbNaxKE/T15VvhzIho7mJ2WAv1r8QouQUuzqtpzIGbRn/KXHRUzCtyP0k4+eMKMLFOPzg848WsDarP3v8VYiSy4nFY7ZP7DRd3KttvW5bgVbSeO4jPmTgS6TnnpRwual9BJXSG7bjbfpIMii3bNZ7jWL4zpKT9Jfm8w9RGKLcX9HqkZ3+y60+LtYdhEfBvqsIlWQoIJBXg=
  file_glob: true
  file:
    - dvc*.rpm
    - dvc*.deb
    - dvc*.pkg
  skip_cleanup: true
  on:
    tags: true
    repo: dataversioncontrol/dvc
