language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - git config --global user.email "dvctester@example.com"
  - git config --global user.name "DVC Tester"
  - mkdir -p ~/.aws && printf "[default]\naws_access_key_id = ABCDEFG\naws_secret_access_key = 123456789" > ~/.aws/credentials
script:
  - ./unittests.sh
after_sucess:
  - CODECLIMATE_REPO_TOKEN=b27257bacc4812c8e6d37285ba34559804e4a207bf6932723a1c9966e5807670 codeclimate-test-reporter
