cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv
dist: xenial
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
    - PYENV_ROOT="$HOME/.pyenv"
    - PATH="$PYENV_ROOT/bin:$PATH"
    - PIP_CACHE_DIR="$HOME/.cache/pip"  # unify pip cache location for all platforms
stages:
  - check
  - test
  - build
# Travis doesn't support testing python on Mac yet, so we need
# to workaround it by installing it directly with brew.
#
# Note that we specify language as ruby-2.4.3 to help us satisfy
# fpm dependencies, as travis runs el capitan with an old ruby
# version, that causes fpm to crash.
#
# Each job will use the previous job's `stage` tag if not specified.
jobs:
  include:
  # patch formatting checks
  - name: "Check patch formatting"
    stage: check
    os: linux
    language: python
    python: 3.7
    before_install:
    install:
    script: ./scripts/ci/check_patch.sh
  # test jobs
  - name: "3.7 on Windows"
    stage: test
    os: windows           # Windows 10.0.17134 N/A Build 17134
    language: shell       # 'language: python' is an error on Travis CI Windows
    env:
      - PYTHON_VERSION=3.7.5
      - PATH=/c/Python37:/c/Python37/Scripts:$PATH
  - name: "3.8 on Windows"
    os: windows           # Windows 10.0.17134 N/A Build 17134
    language: shell       # 'language: python' is an error on Travis CI Windows
    env:
      - PYTHON_VERSION=3.8.0
      - PATH=/c/Python38:/c/Python38/Scripts:$PATH
  - name: "3.5 on Linux"
    language: python
    python: 3.5
  - name: "3.6 on Linux"
    language: python
    python: 3.6
  - name: "3.7 on Linux"
    language: python
    python: 3.7
  - name: "3.8 on Linux"
    language: python
    python: 3.8
  - name: "3.7 on Mac"
    os: osx
    osx_image: xcode11.3
  # build jobs
  - name: "Mac pkg"
    stage: build
    os: osx
    osx_image: xcode9.4
    language: ruby
    rvm: 2.4.3
    install:
    script: ./scripts/build_posix.sh
  - name: "Windows pkg"
    os: windows
    language: shell
    install:
    script: ./scripts/build_windows.cmd
    env:
      - PYTHON_VERSION=3.7.5
      - PATH=/c/Python37:/c/Python37/Scripts:$PATH
  - name: "Linux pkgs"
    language: python
    python: 3.7
    before_install:
    install:
    script: ./scripts/build_posix.sh
  - name: "PyPI pkgs"
    language: python
    python: 3.8
    script: ./scripts/build_package.sh
  - name: Snapcraft snap
    language: python
    python: 3.8
    addons:
     snaps:
     - name: snapcraft
       channel: stable
       confinement: classic
     - name: review-tools
       channel: stable
     - name: lxd
       channel: stable
    env:
    - SNAPCRAFT_IMAGE_INFO: '{"build_url": "$TRAVIS_BUILD_URL"}'
    install:
    - sudo /snap/bin/lxd.migrate -yes
    - sudo /snap/bin/lxd waitready
    - sudo /snap/bin/lxd init --auto
    script:
    - ./scripts/build_snap.sh
    after_failure:
    - sudo journalctl -u snapd

before_install:
  - bash ./scripts/ci/before_install.sh
  - source env.sh
  - bash ./scripts/ci/check_python.sh
install:
  - bash ./scripts/ci/install.sh
script:
  - bash ./scripts/ci/script.sh
deploy:
  - provider: releases
    api_key:
      secure: nyo17gF4Xl6DFL/KVkMewC805Cv+eK99L7SiYCU+WUAYDIzzFL3YJm7fm8bznPeor7DmpO7uSLSveMnJETBtdurW6JWhCTUss4yD66yFzpk6Z5cvHf/1UA5pdMHkkMM54fRaTRt6L2Yal7RPwGEQTBECLXW1Xmf78Y6+0l8lTvXQ9jXOQSRO/63VDKI5Zww2+XytVicUFlr0hLMGKUuaCjjXcQlAPzBgQz3/5Iz6EtzeTf2o+gTPjocbRbSFPikfiBXUn8XlJ8jBj7i114XJRJffw59KxYGDzxp+enfLBULGNoW0Np2hZqkKkPUIdB08C8XVbRXlFYX8cEYBczjqhv8A05p5F5CnltnqQ0KazcoUP2awPVqn68dWNRF+kqrnMBus8euYKIZ4dy/6bVEKJRa84ESJXZVDcwXTAXRqyovSxOlXqg9ZgAImMKBfKn/fpDX2xIvQPaXcnJxKbmcePfdbC1d0HYJ5jkbNaxKE/T15VvhzIho7mJ2WAv1r8QouQUuzqtpzIGbRn/KXHRUzCtyP0k4+eMKMLFOPzg848WsDarP3v8VYiSy4nFY7ZP7DRd3KttvW5bgVbSeO4jPmTgS6TnnpRwual9BJXSG7bjbfpIMii3bNZ7jWL4zpKT9Jfm8w9RGKLcX9HqkZ3+y60+LtYdhEfBvqsIlWQoIJBXg=
    file_glob: true
    file:
      - dvc*.rpm
      - dvc*.deb
      - dvc*.pkg
      - dvc*.exe
    skip_cleanup: true
    on:
      condition: "$(./scripts/ci/deploy_condition.sh dvc*.rpm dvc*.deb dvc*.pkg dvc*.exe)"
      tags: true
      repo: iterative/dvc
      stage: build
  - provider: pypi
    user:
      secure: "IOzNfgPoG3ICg3+s4AuZCCnawgd/KqMzeiAB9R0B9Xb6ProPQJp9O3GBZrtg5OJMHdWQQtwULeOh/LWk4sFdXMcX1iNEgm5Tb7DwO7TDtltW14jUgN9AqfY2twj4UIsW/ON8w0P8v36ZoQq1kO6Pfgjijdm3w+9h6rpps8rJ6jXYpVZVO+SSzzijWddanMkEz4GgctZ2r7U5MWlmm1UogF60kEZIZCQykz0yJnhTpP9nMFDKw6Maki/mcfVwTQ/v3RqjzttHei/aaEMGQXYr3TOX8NPYJXerBpjShDZqcgcCfqPzhi7uCwVYaPvRsMMYH5jgtMz/SO3J6ToeGKT0f1F1ihRyCdusg325TMK7Vv8yHJzL4ngeUbb/oqxWtxhLY7f77Lkx6hBwe6ROpTqiQHIfZad5qyIHihKcDcIHo4FwLHVzxR4y+Ds2js5dXwBkUBaEAx0Dmc6ZdgXqxd815GDwv+VVpzXJhtO6qXmKE36F/Oe6eCNG3dk5MdOK4C2DrM9M8MXllqeQtX6JrM2stWlBalAc9Jn4b0xxAoghX3x3G3hNsLc9Uist1VinY2+IcPozusqj66c+Vbi5YngWSbICOjlIcq2GaOlBi3xioGts396442ztf1eLjMVuvykCI3b4Yz/vJYZOZjUvG/6nLfaFQTJLSXkTvI4do3foeY4="
    password:
      secure: "ts/3FSPL+w4euXryip9wCJWUqUwuJ2CqHi0nEpYVM10KL0cp9aMkQXN/7C8ih+j/JZ25kaO+tis1nx0JERVnKrg/1F/fJhxHTpakCP4OSIlhKRXDt7yUUHcKKt5QdM2XCKhApptP6RTpWL1vlc36CMrhdvTcMYp7hlDOiWjdhhim24FGQzabL42Ko59ttyyCROqgcnjHqj+WlhJl7iYO+lv2PLOtslpkIYY5EMjgBLuGyOvxTqZsAXtworsASdB2CrsTE6iMRcrM1afgkyBlUqDezoiv9TwfZrZ85oRoAxPB7su4QWK7lEP0wGQV/SDz/RL7c+cNfRaauxUKVcC8I2LfaEpudv8vi205+v/08wzPbS4xSOnf89irUJnyGxUy+bYLoXPPVPMyzcQRAUnrQl+ENCmN62HU+/2pkIyiUJvt0wYYP0vp+3pIbXbYQGmAIMq7nZJd7K3rikfnQIGKI03xZsFe3PEdjzhDI9Ej/tRUbJx4pgg084QuYYca6MSYn/zJ5pqIG4A7ngCSxoxoWZT0duo8PrUWQeT17L73Q86HeEv3OzZhWfEF2fNDN3Qbsu4CllSZnbE7DXgAuysTwTYHS/na6lp7wejOqdRUXrHbidVla9Mwxyc9JdWNWzUDxALvNxAdNbV6l85mO8izy8wjQF6M1O7idqTfjQeR4pc="
    skip_existing: true
    file_glob: true
    file:
      - dist/dvc*.whl
      - dist/dvc*.tar.gz
    skip_cleanup: true
    on:
      condition: "$(./scripts/ci/deploy_condition.sh dist/dvc*.whl dist/dvc*.tar.gz)"
      tags: true
      repo: iterative/dvc
      stage: build
  - provider: script
    skip_cleanup: true
    script: "timeout 600 snapcraft push dvc_*.snap --release $SNAP_CHANNEL || echo timed out"
    on:
      all_branches: true
      condition: "$(./scripts/ci/deploy_condition.sh dvc_*.snap) && ($TRAVIS_BRANCH = master || -n $TRAVIS_TAG)"
      repo: iterative/dvc
      stage: build
