language: python
sudo: required
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5"
#  - "3.6" Not supported by pyinstaller yet
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - git config --global user.email "dvctester@example.com"
  - git config --global user.name "DVC Tester"
  - mkdir -p ~/.aws && printf "[default]\naws_access_key_id = ABCDEFG\naws_secret_access_key = 123456789" > ~/.aws/credentials
script:
  - ./unittests.sh
  - ./build_linux.sh
  - ./build_package.sh
after_sucess:
  - CODECLIMATE_REPO_TOKEN=7350efa14a67c3911af96dadaabe811b43eead7b466309b47687499bf5d72287 codeclimate-test-reporter
