name: Lint Python

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run: pip install ".[all,tests]" Pygments collective.checkdocs pre-commit
    - name: Check README
      run: python setup.py checkdocs
    - name: Check formatting
      run: pre-commit run --all-files
