name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  DVC_TEST: "true"
  HOMEBREW_NO_AUTO_UPDATE: 1
  SHELL: /bin/bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python 3.8
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        pip install wheel
        pip install ".[all,tests]" Pygments collective.checkdocs pre-commit
    - name: install temporary dependencies
      run: |
        pip install git+https://github.com/isidentical/gdrivefs@service-account
        pip install git+https://github.com/isidentical/pydata-google-auth@service-account
    - name: Check README
      run: python setup.py checkdocs
    - uses: pre-commit/action@v2.0.3
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        pyv: ["3.6", "3.7", "3.8", "3.9"]
# macos 11.0 workers take too long to start up
#        include:
#          - os: "macos-11.0"
#            pyv: "3.9"
        exclude:
          - os: macos-10.15
            pyv: "3.9"

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.pyv }}
    - name: get pip cache dir
      id: pip-cache-dir
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: set pip cache
      id: pip-cache
      uses: actions/cache@v2.1.5
      with:
        path: ${{ steps.pip-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: install
      if: steps.cache.pip-cache-dir.cache-hit != 'true'
      run: |
        pip install wheel
        pip install -e ".[all,tests]"
    - name: install temporary dependencies
      run: |
        pip install git+https://github.com/isidentical/gdrivefs@service-account
        pip install git+https://github.com/isidentical/pydata-google-auth@service-account
    - name: setup git
      run: |
        git config --global user.email "dvctester@example.com"
        git config --global user.name "DVC Tester"
    - name: setup gs creds
      shell: bash
      env:
        GS_CREDS_JSON: ${{ secrets.GS_CREDS_JSON }}
      if: env.GS_CREDS_JSON != ''
      run: |
        mkdir -p scripts/ci
        echo "$GS_CREDS_JSON" > scripts/ci/gcp-creds.json
    - name: run tests
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: python -m tests --all --cov-report=xml --cov-report=term -n=4
    - name: upload coverage report
      uses: codecov/codecov-action@v1.5.0
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
  notify:
    if: github.ref == 'refs/heads/master' && failure()
    needs:
      - lint
      - tests
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'CI Failed on master :boom:'
        SLACK_TITLE: CI Status
        SLACK_USERNAME: DVC-CI
